---
title: 'Pattern 4: Missions Decomposition'
output:
  html_document:
    df_print: paged
---

# Mission Deploys Component (One Level)

## Raw Query

```{r}
library(SPARQL, quietly=TRUE)

endpointURL = "http://localhost:3030/oml-tutorial"
queryString1 = "
PREFIX base:        <http://opencaesar.io/tutorial/vocabulary/base#>
PREFIX mission:     <http://opencaesar.io/tutorial/vocabulary/mission#>

SELECT DISTINCT ?m_id ?m_name ?c_id ?c_name

WHERE {
	[] a mission:Mission ;
    base:hasIdentifier ?m_id ;
    base:hasCanonicalName ?m_name ;
    mission:deploys [
      base:hasIdentifier ?c_id ;
      base:hasCanonicalName ?c_name ;
    ]
}
ORDER BY ?m_id ?c_id
"
d1 <- SPARQL(url=endpointURL, query=queryString1)
d1$results
```

# Mission Deploys/Contains* Component (Transitive Closure)
```{r}
endpointURL = "http://localhost:3030/oml-tutorial"
queryString1 = "
PREFIX base:        <http://opencaesar.io/tutorial/vocabulary/base#>
PREFIX mission:     <http://opencaesar.io/tutorial/vocabulary/mission#>

SELECT DISTINCT ?m_id ?m_name ?c_id ?c_name

WHERE {
	[] a mission:Mission ;
    base:hasIdentifier ?m_id ;
    base:hasCanonicalName ?m_name ;
    mission:deploys / base:contains* [
      base:hasIdentifier ?c_id ;
      base:hasCanonicalName ?c_name ;
    ]
}
ORDER BY ?m_id ?c_id
"
d1 <- SPARQL(url=endpointURL, query=queryString1)
d1$results
```
