PREFIX uml:        <http://www.eclipse.org/uml2/5.0.0/UML#>
PREFIX base:        <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX mission:     <http://imce.jpl.nasa.gov/foundation/mission#>

SELECT DISTINCT ?o_id ?o_name

WHERE {
	?o
      a uml:Class ;
      a mission:Objective ;
      base:hasIdentifier ?o_id ;
      base:hasCanonicalName ?o_name ;
}
ORDER BY ?o_id